#include "Graph.h"
#include "BFS.cpp"
#include "DFS.cpp"
#include "Graph.cpp"
#include "log.h"
#include "MST-Kruskal.cpp"
#include "MST-Prim.cpp"
#include "SP-Dijkstra.cpp"
#include "SP-Floyd.cpp"
// #include "TopologicalSort.cpp"